# Generated by Django 6.1 on 2026-08-22 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cursos',
            name='nombre',
            field=models.CharField(max_length=150),
        ),
    ]
